services:
  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MINIO_PUBLIC_ENDPOINT: 188.166.65.112:9000
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: nexclone-frontend
    ports:
      - "3000:3000"
    env_file:
      - .dev.env
    networks:
      - nexclone_network
    depends_on:
      - backend

  # ASP.NET Core API & Admin
  backend:
    build:
      context: ./NexClone.Backend
      dockerfile: Dockerfile
    container_name: nexclone-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - .dev.env
    networks:
      - nexclone_network
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:15
    container_name: nexclone-postgres
    env_file:
      - .dev.env
    ports:
      - "5432:5432"
    networks:
      - nexclone_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: nexclone-minio
    ports:
      - "9001:9001"
      - "9002:9002"
    env_file:
      - .dev.env
    command: server /data --address ":9001" --console-address ":9002"
    networks:
      - nexclone_network
    volumes:
      - miniodata:/data


networks:
  nexclone_network:
    driver: bridge

volumes:
  pgdata:
  miniodata:
