INSERT INTO text_to_voice_darijatstyle (name, value, is_premium, is_active, "order") VALUES 
('طرب', 'طرب', false, true, 45),
('شعبي', 'شعبي', false, true, 46),
('بوب عربي', 'بوب عربي', false, true, 47),
('روك عربي', 'روك عربي', false, true, 48),
('كلاسيكي', 'كلاسيكي', false, true, 49),
('أوبرا', 'أوبرا', false, true, 50),
('إنشاد ديني', 'إنشاد ديني', false, true, 51),
('شيلات', 'شيلات', false, true, 52),
('موال', 'موال', false, true, 53),
('جاز عربي', 'جاز عربي', false, true, 54),
('فرانكو بوب', 'فرانكو بوب', false, true, 55),
('هيب هوب عربي', 'هيب هوب عربي', false, true, 56),
('لوفي', 'لوفي', false, true, 57),
('أر أند بي عربي', 'أر أند بي عربي', false, true, 58),
('عراقي', 'عراقي', false, true, 59),
('خليجي', 'خليجي', false, true, 60),
('راي', 'راي', false, true, 61),
('ميكس شرقي وغربي', 'ميكس شرقي وغربي', false, true, 62);

INSERT INTO text_to_voice_darijatemotion (name, value, is_premium, is_active, "order") VALUES 
('مرح', 'مرح', false, true, 15),
('متفائل', 'متفائل', false, true, 16),
('متشائم', 'متشائم', false, true, 17),
('مرتبك', 'مرتبك', false, true, 18),
('غيور', 'غيور', false, true, 19),
('نادم', 'نادم', false, true, 20),
('فخور', 'فخور', false, true, 21),
('محبط', 'محبط', false, true, 22),
('مصدوم', 'مصدوم', false, true, 23),
('متعب', 'متعب', false, true, 24),
('ملان', 'ملان', false, true, 25),
('متمرد', 'متمرد', false, true, 26),
('بريء', 'بريء', false, true, 27),
('شرير', 'شرير', false, true, 28),
('غامض', 'غامض', false, true, 29),
('متحسر', 'متحسر', false, true, 30),
('متوسل', 'متوسل', false, true, 31);
