http:
  routers:
    frontend-router:
      rule: "Host(`dev.169.58.204.169.nip.io`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
      service: frontend-service
    backend-router:
      rule: "Host(`api.169.58.204.169.nip.io`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
      service: backend-service

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
    backend-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8080"
