using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexClone.Backend.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreateBaseline : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ApiConfigurations"" (
        ""Id"" uuid NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""ApiKey"" character varying(500) NOT NULL,
        ""BaseUrl"" character varying(255),
        ""IsActive"" boolean NOT NULL,
        ""AdditionalSettings"" text,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_ApiConfigurations"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AppSettings"" (
        ""Key"" character varying(100) NOT NULL,
        ""Value"" text NOT NULL,
        ""Description"" character varying(200) NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_AppSettings"" PRIMARY KEY (""Key"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetRoles"" (
        ""Id"" uuid NOT NULL,
        ""Name"" character varying(256),
        ""NormalizedName"" character varying(256),
        ""ConcurrencyStamp"" text,
        CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetUsers"" (
        ""Id"" uuid NOT NULL,
        ""FullName"" text NOT NULL,
        ""Country"" text NOT NULL,
        ""IsVerified"" boolean NOT NULL,
        ""LastVerificationEmailSentAt"" timestamp with time zone,
        ""ImageUrl"" text,
        ""IsActive"" boolean NOT NULL,
        ""IsStaff"" boolean NOT NULL,
        ""IsSuperAdmin"" boolean NOT NULL,
        ""VisibleAdminSections"" text,
        ""StandardCredits"" numeric NOT NULL,
        ""PremiumCredits"" numeric NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UserName"" character varying(256),
        ""NormalizedUserName"" character varying(256),
        ""Email"" character varying(256),
        ""NormalizedEmail"" character varying(256),
        ""EmailConfirmed"" boolean NOT NULL,
        ""PasswordHash"" text,
        ""SecurityStamp"" text,
        ""ConcurrencyStamp"" text,
        ""PhoneNumber"" text,
        ""PhoneNumberConfirmed"" boolean NOT NULL,
        ""TwoFactorEnabled"" boolean NOT NULL,
        ""LockoutEnd"" timestamp with time zone,
        ""LockoutEnabled"" boolean NOT NULL,
        ""AccessFailedCount"" integer NOT NULL,
        CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AvatarToVideoModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""UnitCost"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_AvatarToVideoModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AvatarToVideoSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxImageFileSizeMb"" bigint NOT NULL,
        ""MaxAudioFileSizeMb"" bigint NOT NULL,
        ""MaxPromptLength"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_AvatarToVideoSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""BlogPosts"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Title"" text NOT NULL,
        ""Content"" text NOT NULL,
        ""MediaUrl"" text NOT NULL,
        ""MediaType"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""IsPublished"" boolean NOT NULL,
        CONSTRAINT ""PK_BlogPosts"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""CustomPages"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Slug"" character varying(100) NOT NULL,
        ""TitleEn"" text NOT NULL,
        ""TitleAr"" text NOT NULL,
        ""ContentEn"" text NOT NULL,
        ""ContentAr"" text NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_CustomPages"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""DataProtectionKeys"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""FriendlyName"" text,
        ""Xml"" text,
        CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""EmailTemplates"" (
        ""Id"" uuid NOT NULL,
        ""Name"" character varying(100) NOT NULL,
        ""Subject"" character varying(255) NOT NULL,
        ""HtmlBody"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_EmailTemplates"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ImageToVideoModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""CostPerSecond_480p"" numeric NOT NULL,
        ""CostPerSecond_720p"" numeric NOT NULL,
        ""CostPerSecond_1080p"" numeric NOT NULL,
        ""CostPerSecond_4k"" numeric NOT NULL,
        ""FixedCost_480p"" numeric NOT NULL,
        ""FixedCost_720p"" numeric NOT NULL,
        ""FixedCost_1080p"" numeric NOT NULL,
        ""FixedCost_4k"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_ImageToVideoModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ImageToVideoSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxImageFileSizeMb"" bigint NOT NULL,
        ""MaxDurationSeconds"" integer NOT NULL,
        ""MaxPromptLength"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_ImageToVideoSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""LipSyncModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""CostPerSecond"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_LipSyncModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""LipSyncSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxVideoFileSizeMb"" bigint NOT NULL,
        ""MaxAudioFileSizeMb"" bigint NOT NULL,
        ""MaxAudioDurationSeconds"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_LipSyncSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ManualPaymentMethods"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Name"" character varying(100) NOT NULL,
        ""AccountDetails"" character varying(200) NOT NULL,
        ""Instructions"" character varying(500),
        ""IsActive"" boolean NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_ManualPaymentMethods"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""MotionControlModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""CostPerGeneration"" numeric NOT NULL,
        ""CostPerSecond"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_MotionControlModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""MotionControlSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxVideoFileSizeMb"" bigint NOT NULL,
        ""MaxImageFileSizeMb"" bigint NOT NULL,
        ""MaxDurationSeconds"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_MotionControlSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""PaymentGatewayConfigs"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ProviderName"" text NOT NULL,
        ""PublicKey"" text,
        ""SecretKey"" text,
        ""HmacSecret"" text,
        ""IntegrationId"" text,
        ""WalletIntegrationId"" text,
        ""IframeId"" text,
        ""ClientId"" text,
        ""ClientSecret"" text,
        ""ApiBase"" text,
        ""IsActive"" boolean NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_PaymentGatewayConfigs"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""Plans"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Name"" character varying(255) NOT NULL,
        ""NameAr"" character varying(255) NOT NULL,
        ""Description"" character varying(1000),
        ""DescriptionAr"" character varying(1000),
        ""Features"" text,
        ""FeaturesAr"" text,
        ""DurationDays"" integer NOT NULL,
        ""GracePeriodDays"" integer NOT NULL,
        ""PriceUsd"" numeric NOT NULL,
        ""PriceEgp"" numeric NOT NULL,
        ""TaxPercentageUsd"" numeric NOT NULL,
        ""TaxPercentageEgp"" numeric NOT NULL,
        ""FixedFeeUsd"" numeric NOT NULL,
        ""FixedFeeEgp"" numeric NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""MonthlyCredits"" numeric NOT NULL,
        ""StandardCredits"" numeric NOT NULL,
        ""PremiumCredits"" numeric NOT NULL,
        ""TextToImageEnabled"" boolean NOT NULL,
        ""TextToVideoEnabled"" boolean NOT NULL,
        ""ImageToVideoEnabled"" boolean NOT NULL,
        ""ReferenceToVideoEnabled"" boolean NOT NULL,
        ""LipSyncEnabled"" boolean NOT NULL,
        ""MotionControlEnabled"" boolean NOT NULL,
        ""SttEnabled"" boolean NOT NULL,
        ""TtsEnabled"" boolean NOT NULL,
        ""AvatarVideoEnabled"" boolean NOT NULL,
        ""IsFreeTrial"" boolean NOT NULL,
        ""AllowedVoices"" text,
        ""IsDefaultRegistrationPlan"" boolean NOT NULL,
        ""AffiliateFirstCommissionType"" character varying(50) NOT NULL,
        ""AffiliateFirstCommissionValueUsd"" numeric NOT NULL,
        ""AffiliateFirstCommissionValueEgp"" numeric NOT NULL,
        ""AffiliateRecurringCommissionType"" character varying(50) NOT NULL,
        ""AffiliateRecurringCommissionValueUsd"" numeric NOT NULL,
        ""AffiliateRecurringCommissionValueEgp"" numeric NOT NULL,
        ""IsDeleted"" boolean NOT NULL,
        CONSTRAINT ""PK_Plans"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""SystemUpdates"" (
        ""Id"" uuid NOT NULL,
        ""TitleAr"" character varying(255) NOT NULL,
        ""DescriptionAr"" text NOT NULL,
        ""TitleEn"" character varying(255) NOT NULL,
        ""DescriptionEn"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_SystemUpdates"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToImageModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""CostPerImage"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_TextToImageModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToImageSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxPromptLength"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_TextToImageSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToVideoModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""CostPerSecond_480p"" numeric NOT NULL,
        ""CostPerSecond_720p"" numeric NOT NULL,
        ""CostPerSecond_1080p"" numeric NOT NULL,
        ""CostPerSecond_4k"" numeric NOT NULL,
        ""FixedCost_480p"" numeric NOT NULL,
        ""FixedCost_720p"" numeric NOT NULL,
        ""FixedCost_1080p"" numeric NOT NULL,
        ""FixedCost_4k"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_TextToVideoModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToVideoSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxPromptLength"" integer NOT NULL,
        ""MaxDurationSeconds"" integer NOT NULL,
        ""DefaultResolution"" character varying(20) NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_TextToVideoSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToVoiceModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""QualityLevel"" character varying(50) NOT NULL,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""CostPerChar"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_TextToVoiceModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TextToVoiceSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxTextLength"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""FallbackThresholdLimit"" integer,
        ""FallbackResetDurationHours"" integer,
        ""CurrentPrimaryRequestCount"" integer NOT NULL,
        ""LastResetDate"" timestamp with time zone,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_TextToVoiceSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ToolConfigurations"" (
        ""Id"" uuid NOT NULL,
        ""ToolName"" character varying(100) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""IsMaintenanceMode"" boolean NOT NULL,
        ""IsComingSoon"" boolean NOT NULL,
        ""AllowStandardCredits"" boolean NOT NULL,
        ""AllowPremiumCredits"" boolean NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        ""AdditionalSettings"" jsonb,
        CONSTRAINT ""PK_ToolConfigurations"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""VoiceToTextModelPricings"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ModelName"" character varying(100) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""BillingType"" character varying(50) NOT NULL,
        ""CostPerMinute"" numeric NOT NULL,
        ""CostPerSecond"" numeric NOT NULL,
        ""BaseCost"" numeric NOT NULL,
        ""AllowedWallet"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_VoiceToTextModelPricings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""VoiceToTextSettings"" (
        ""Id"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""MaxAudioFileSizeMb"" bigint NOT NULL,
        ""MaxAudioDurationMinutes"" integer NOT NULL,
        ""MaxConcurrentOperations"" integer NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_VoiceToTextSettings"" PRIMARY KEY (""Id"")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetRoleClaims"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""RoleId"" uuid NOT NULL,
        ""ClaimType"" text,
        ""ClaimValue"" text,
        CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AffiliateProfiles"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""UserId"" uuid NOT NULL,
        ""AffiliateDisplayId"" character varying(20) NOT NULL,
        ""ReferralCode"" character varying(50) NOT NULL,
        ""IsActive"" boolean NOT NULL,
        ""TotalClicks"" integer NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""MobileNumber"" character varying(20),
        ""TelegramUsername"" character varying(100),
        ""WhatsappNumber"" character varying(20),
        ""FacebookAccount"" character varying(200),
        ""PolicyAcceptedAt"" timestamp with time zone,
        CONSTRAINT ""PK_AffiliateProfiles"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AffiliateProfiles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetUserClaims"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""UserId"" uuid NOT NULL,
        ""ClaimType"" text,
        ""ClaimValue"" text,
        CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetUserLogins"" (
        ""LoginProvider"" text NOT NULL,
        ""ProviderKey"" text NOT NULL,
        ""ProviderDisplayName"" text,
        ""UserId"" uuid NOT NULL,
        CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
        CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetUserRoles"" (
        ""UserId"" uuid NOT NULL,
        ""RoleId"" uuid NOT NULL,
        CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
        CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AspNetUserTokens"" (
        ""UserId"" uuid NOT NULL,
        ""LoginProvider"" text NOT NULL,
        ""Name"" text NOT NULL,
        ""Value"" text,
        CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
        CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""DeviceFingerprints"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""UserId"" uuid NOT NULL,
        ""IpAddress"" text NOT NULL,
        ""UserAgent"" text NOT NULL,
        ""FingerprintHash"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_DeviceFingerprints"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_DeviceFingerprints_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""EmailVerifications"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Token"" character varying(100) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""IsUsed"" boolean NOT NULL,
        ""UserId"" uuid NOT NULL,
        CONSTRAINT ""PK_EmailVerifications"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_EmailVerifications_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""GenerationHistories"" (
        ""Id"" uuid NOT NULL,
        ""UserId"" uuid NOT NULL,
        ""Type"" character varying(50) NOT NULL,
        ""Title"" character varying(255) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""Duration"" character varying(20) NOT NULL,
        ""Status"" character varying(20) NOT NULL,
        ""Lang"" character varying(50) NOT NULL,
        ""Voice"" character varying(100) NOT NULL,
        ""FileUrl"" character varying(1000) NOT NULL,
        ""ResultText"" text NOT NULL,
        ""InputText"" text NOT NULL,
        ""CreditsUsed"" numeric NOT NULL,
        ""IsDeletedByUser"" boolean NOT NULL,
        ""ErrorMessage"" character varying(2000),
        CONSTRAINT ""PK_GenerationHistories"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_GenerationHistories_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""PhoneNumbers"" (
        ""Id"" uuid NOT NULL,
        ""PhoneNumber"" character varying(20) NOT NULL,
        ""TermsAccepted"" boolean NOT NULL,
        ""TermsAcceptedAt"" timestamp with time zone,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UserId"" uuid NOT NULL,
        CONSTRAINT ""PK_PhoneNumbers"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_PhoneNumbers_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""RefreshTokens"" (
        ""Id"" uuid NOT NULL,
        ""UserId"" uuid NOT NULL,
        ""Token"" text NOT NULL,
        ""ExpiresAt"" timestamp with time zone NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""CreatedByIp"" text,
        ""IsRevoked"" boolean NOT NULL,
        ""RevokedAt"" timestamp with time zone,
        ""RevokedByIp"" text,
        ""ReplacedByToken"" text,
        CONSTRAINT ""PK_RefreshTokens"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_RefreshTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""SupportTickets"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""UserId"" uuid NOT NULL,
        ""Subject"" character varying(200) NOT NULL,
        ""Status"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_SupportTickets"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_SupportTickets_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""BlogComments"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""BlogPostId"" integer NOT NULL,
        ""UserId"" uuid,
        ""Content"" text NOT NULL,
        ""IsAdminReply"" boolean NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_BlogComments"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_BlogComments_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id""),
        CONSTRAINT ""FK_BlogComments_BlogPosts_BlogPostId"" FOREIGN KEY (""BlogPostId"") REFERENCES ""BlogPosts"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""PlanPaymentGateways"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""PlanId"" integer NOT NULL,
        ""GatewayConfigId"" integer NOT NULL,
        ""Currency"" character varying(10) NOT NULL,
        ""DisplayName"" character varying(100),
        ""IsDefault"" boolean NOT NULL,
        ""SortOrder"" integer NOT NULL,
        ""IsActive"" boolean NOT NULL,
        CONSTRAINT ""PK_PlanPaymentGateways"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_PlanPaymentGateways_PaymentGatewayConfigs_GatewayConfigId"" FOREIGN KEY (""GatewayConfigId"") REFERENCES ""PaymentGatewayConfigs"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_PlanPaymentGateways_Plans_PlanId"" FOREIGN KEY (""PlanId"") REFERENCES ""Plans"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""Subscriptions"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""StartDate"" timestamp with time zone NOT NULL,
        ""EndDate"" timestamp with time zone NOT NULL,
        ""Status"" character varying(10) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UserId"" uuid NOT NULL,
        ""PlanId"" integer NOT NULL,
        CONSTRAINT ""PK_Subscriptions"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Subscriptions_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Subscriptions_Plans_PlanId"" FOREIGN KEY (""PlanId"") REFERENCES ""Plans"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""ToolRoutingRules"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""ToolConfigurationId"" uuid NOT NULL,
        ""QualityLevel"" character varying(50) NOT NULL,
        ""ProviderName"" character varying(100) NOT NULL,
        ""ModelName"" character varying(100) NOT NULL,
        ""ActiveFromTime"" interval,
        ""ActiveToTime"" interval,
        ""MaxDailyRequests"" integer,
        ""MaxRequestsPerMinute"" integer,
        CONSTRAINT ""PK_ToolRoutingRules"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_ToolRoutingRules_ToolConfigurations_ToolConfigurationId"" FOREIGN KEY (""ToolConfigurationId"") REFERENCES ""ToolConfigurations"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AffiliatePayouts"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""AffiliateProfileId"" integer NOT NULL,
        ""Amount"" numeric NOT NULL,
        ""Currency"" character varying(10) NOT NULL,
        ""PayoutMethod"" character varying(100) NOT NULL,
        ""PayoutAccount"" character varying(300) NOT NULL,
        ""AffiliateMessage"" character varying(500),
        ""Status"" character varying(20) NOT NULL,
        ""RejectionReason"" character varying(500),
        ""RequestedAt"" timestamp with time zone NOT NULL,
        ""ProcessedAt"" timestamp with time zone,
        ""TransferReceiptUrl"" character varying(1000),
        CONSTRAINT ""PK_AffiliatePayouts"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AffiliatePayouts_AffiliateProfiles_AffiliateProfileId"" FOREIGN KEY (""AffiliateProfileId"") REFERENCES ""AffiliateProfiles"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AffiliateReferrals"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""AffiliateProfileId"" integer NOT NULL,
        ""ReferredUserId"" uuid,
        ""SessionToken"" character varying(100),
        ""ClickedAt"" timestamp with time zone NOT NULL,
        ""AttributionExpiresAt"" timestamp with time zone NOT NULL,
        ""HasConverted"" boolean NOT NULL,
        CONSTRAINT ""PK_AffiliateReferrals"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AffiliateReferrals_AffiliateProfiles_AffiliateProfileId"" FOREIGN KEY (""AffiliateProfileId"") REFERENCES ""AffiliateProfiles"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_AffiliateReferrals_AspNetUsers_ReferredUserId"" FOREIGN KEY (""ReferredUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""TicketMessages"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""TicketId"" integer NOT NULL,
        ""SenderId"" uuid,
        ""Content"" text NOT NULL,
        ""AttachmentUrl"" text NOT NULL,
        ""AttachmentType"" text NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""IsAdminMessage"" boolean NOT NULL,
        CONSTRAINT ""PK_TicketMessages"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_TicketMessages_AspNetUsers_SenderId"" FOREIGN KEY (""SenderId"") REFERENCES ""AspNetUsers"" (""Id""),
        CONSTRAINT ""FK_TicketMessages_SupportTickets_TicketId"" FOREIGN KEY (""TicketId"") REFERENCES ""SupportTickets"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""Invoices"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""InvoiceNumber"" character varying(50) NOT NULL,
        ""SubscriptionId"" integer NOT NULL,
        ""UserId"" uuid NOT NULL,
        ""PaymentGateway"" character varying(50) NOT NULL,
        ""PaymentMethod"" character varying(50) NOT NULL,
        ""TransactionId"" character varying(100),
        ""Currency"" character varying(10) NOT NULL,
        ""SubTotal"" numeric NOT NULL,
        ""TaxAmount"" numeric NOT NULL,
        ""FixedFeeAmount"" numeric NOT NULL,
        ""TotalAmount"" numeric NOT NULL,
        ""MinioPdfUrl"" character varying(1000),
        ""VerificationToken"" character varying(100) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_Invoices"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Invoices_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Invoices_Subscriptions_SubscriptionId"" FOREIGN KEY (""SubscriptionId"") REFERENCES ""Subscriptions"" (""Id"") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""Payments"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""PaymentId"" character varying(255) NOT NULL,
        ""Amount"" numeric NOT NULL,
        ""Currency"" character varying(10) NOT NULL,
        ""Method"" character varying(20) NOT NULL,
        ""Status"" character varying(10) NOT NULL,
        ""Notes"" character varying(300),
        ""ReceiptUrl"" character varying(500),
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""UpdatedAt"" timestamp with time zone NOT NULL,
        ""UserId"" uuid NOT NULL,
        ""PlanId"" integer,
        ""SubscriptionId"" integer,
        CONSTRAINT ""PK_Payments"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_Payments_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
        CONSTRAINT ""FK_Payments_Plans_PlanId"" FOREIGN KEY (""PlanId"") REFERENCES ""Plans"" (""Id"") ON DELETE SET NULL,
        CONSTRAINT ""FK_Payments_Subscriptions_SubscriptionId"" FOREIGN KEY (""SubscriptionId"") REFERENCES ""Subscriptions"" (""Id"") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE TABLE ""AffiliateCommissions"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""AffiliateProfileId"" integer NOT NULL,
        ""AffiliateReferralId"" integer NOT NULL,
        ""CustomerId"" uuid NOT NULL,
        ""PlanId"" integer NOT NULL,
        ""SubscriptionId"" integer NOT NULL,
        ""PaymentId"" integer NOT NULL,
        ""Type"" character varying(20) NOT NULL,
        ""Amount"" numeric NOT NULL,
        ""Currency"" character varying(10) NOT NULL,
        ""Rate"" numeric NOT NULL,
        ""Status"" character varying(20) NOT NULL,
        ""CreatedAt"" timestamp with time zone NOT NULL,
        ""AvailableAt"" timestamp with time zone NOT NULL,
        ""PaidAt"" timestamp with time zone,
        CONSTRAINT ""PK_AffiliateCommissions"" PRIMARY KEY (""Id""),
        CONSTRAINT ""FK_AffiliateCommissions_AffiliateProfiles_AffiliateProfileId"" FOREIGN KEY (""AffiliateProfileId"") REFERENCES ""AffiliateProfiles"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_AffiliateCommissions_AffiliateReferrals_AffiliateReferralId"" FOREIGN KEY (""AffiliateReferralId"") REFERENCES ""AffiliateReferrals"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_AffiliateCommissions_AspNetUsers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_AffiliateCommissions_Payments_PaymentId"" FOREIGN KEY (""PaymentId"") REFERENCES ""Payments"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_AffiliateCommissions_Plans_PlanId"" FOREIGN KEY (""PlanId"") REFERENCES ""Plans"" (""Id"") ON DELETE RESTRICT,
        CONSTRAINT ""FK_AffiliateCommissions_Subscriptions_SubscriptionId"" FOREIGN KEY (""SubscriptionId"") REFERENCES ""Subscriptions"" (""Id"") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_AffiliateProfileId"" ON ""AffiliateCommissions"" (""AffiliateProfileId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_AffiliateReferralId"" ON ""AffiliateCommissions"" (""AffiliateReferralId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_CustomerId"" ON ""AffiliateCommissions"" (""CustomerId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_PaymentId"" ON ""AffiliateCommissions"" (""PaymentId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_PlanId"" ON ""AffiliateCommissions"" (""PlanId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateCommissions_SubscriptionId"" ON ""AffiliateCommissions"" (""SubscriptionId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliatePayouts_AffiliateProfileId"" ON ""AffiliatePayouts"" (""AffiliateProfileId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE UNIQUE INDEX ""IX_AffiliateProfiles_ReferralCode"" ON ""AffiliateProfiles"" (""ReferralCode"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateProfiles_UserId"" ON ""AffiliateProfiles"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateReferrals_AffiliateProfileId"" ON ""AffiliateReferrals"" (""AffiliateProfileId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AffiliateReferrals_ReferredUserId"" ON ""AffiliateReferrals"" (""ReferredUserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AspNetRoleClaims_RoleId"" ON ""AspNetRoleClaims"" (""RoleId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE UNIQUE INDEX ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AspNetUserClaims_UserId"" ON ""AspNetUserClaims"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AspNetUserLogins_UserId"" ON ""AspNetUserLogins"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_AspNetUserRoles_RoleId"" ON ""AspNetUserRoles"" (""RoleId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE UNIQUE INDEX ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_BlogComments_BlogPostId"" ON ""BlogComments"" (""BlogPostId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_BlogComments_UserId"" ON ""BlogComments"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_DeviceFingerprints_UserId"" ON ""DeviceFingerprints"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_EmailVerifications_UserId"" ON ""EmailVerifications"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_GenerationHistories_UserId"" ON ""GenerationHistories"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Invoices_SubscriptionId"" ON ""Invoices"" (""SubscriptionId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Invoices_UserId"" ON ""Invoices"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Payments_PlanId"" ON ""Payments"" (""PlanId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Payments_SubscriptionId"" ON ""Payments"" (""SubscriptionId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Payments_UserId"" ON ""Payments"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE UNIQUE INDEX ""IX_PhoneNumbers_UserId"" ON ""PhoneNumbers"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_PlanPaymentGateways_GatewayConfigId"" ON ""PlanPaymentGateways"" (""GatewayConfigId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_PlanPaymentGateways_PlanId"" ON ""PlanPaymentGateways"" (""PlanId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_RefreshTokens_UserId"" ON ""RefreshTokens"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Subscriptions_PlanId"" ON ""Subscriptions"" (""PlanId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_Subscriptions_UserId"" ON ""Subscriptions"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_SupportTickets_UserId"" ON ""SupportTickets"" (""UserId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_TicketMessages_SenderId"" ON ""TicketMessages"" (""SenderId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_TicketMessages_TicketId"" ON ""TicketMessages"" (""TicketId"");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" = '20260822135520_InitialCreateBaseline') THEN
    CREATE INDEX ""IX_ToolRoutingRules_ToolConfigurationId"" ON ""ToolRoutingRules"" (""ToolConfigurationId"");
    END IF;
END $EF$;
");
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
