apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexclone-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - api-nexclone.167.71.66.188.nip.io
    - app-nexclone.167.71.66.188.nip.io
    secretName: nexclone-tls
  rules:
  - host: api-nexclone.167.71.66.188.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexclone-backend
            port:
              number: 8080
  - host: app-nexclone.167.71.66.188.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexclone-frontend
            port:
              number: 3000
