import api from './api';
import axios from 'axios';

/**
 * Uploads a file directly to MinIO using a Presigned URL.
 * 
 * @param file The file to upload.
 * @returns The unique objectName generated by the backend, which can be saved to the database.
 */
export const uploadDirectToMinio = async (file: File): Promise<string> => {
  try {
    // 1. Request the presigned URL from the .NET Backend
    const response = await api.post('/api/media/upload-url', {
      fileName: file.name,
      contentType: file.type,
    });

    const { url, objectName } = response.data;

    // 2. Upload the file directly to MinIO using the presigned URL
    // We use a clean axios instance to avoid attaching our backend auth tokens/headers to MinIO
    await axios.put(url, file, {
      headers: {
        'Content-Type': file.type,
      },
    });

    // 3. Return the object name so the frontend can send it back to the backend to save in the DB
    return objectName;
  } catch (error) {
    console.error('Error uploading file directly to MinIO:', error);
    throw error;
  }
};
